---
title: "R Notebook"
output: word_document
editor_options: 
  chunk_output_type: console
---

#To Update
```{r}
output_location<-c("T:\\DCEG\\CGF\\TechTransfer\\Microbiome\\Extraction\\Optimization\\Fecal\\Fresh Fecal Optimization_2017.08\\Phase I\\Analysis\\NP0084-MB4,5,6\\R_Complete\\")

taxa_levels<-c("Genus")
reference_db<-"greengenes"

manifest_name<-paste("metadata_",taxa_levels,"_",reference_db,"_seqcontrol.csv",sep="")
taxa_file<-paste("taxa_",taxa_levels,"_",reference_db,"_seqcontrol.csv",sep="")

control_location<-c("T:\\DCEG\\CGF\\TechTransfer\\Microbiome\\Extraction\\Optimization\\Fecal\\Fresh Fecal Optimization_2017.08\\Phase I\\Controls\\Taxonomy\\")
```

#Load required libraries
############### 
```{r}
library("biom")
library(data.table)
library(ggplot2)
library(tm)
library(vegan)
library("biom")
library(tidyr)
library(ggplot2)
library(cowplot)
library(scales)
library(phyloseq)
library(qiime2R)
library(tibble)
library(gridExtra)
library(tidyverse)
```

#Analysis
###############
#Taxonomy Reference - Expected frequencies
```{r}
#Read in controls taxonomy file, grouped by taxa
for (a in taxa_levels){
 control_expect <- read.table(paste(control_location,"Taxonomy_",taxa_levels,"_2019.txt",sep=""),sep="\t",header=TRUE)
 rownames(control_expect) <- unique(control_expect[,taxa_levels])
 
 control_db_name<-paste("expected_taxa_",a,sep="")
 assign(control_db_name,control_expect)
 remove(control_expect)
}

```

#Load OTU and metadata tables
```{r}
for(a in taxa_levels){
 for (b in reference_db){
  metadata_db_name<-paste("metadata_",a,"_",b,sep="")
  
  temp <- read.table(paste(output_location,"Taxa\\",metadata_db_name,"_seqcontrol.csv",sep=""),sep=",",header= TRUE)
  rownames(temp)<-temp$X
  temp<-temp[-1]
  
  assign(metadata_db_name,temp)
  remove(temp)
  
  taxa_db_name<-paste("taxa_",a,"_",b,sep="")
  
  temp<-read.table(paste(output_location,"Taxa\\",taxa_db_name,"_seqcontrol.csv",sep=""),sep=",",header= TRUE)
  rownames(temp)<-temp$X
  temp<-temp[-1]
  
  assign(taxa_db_name,temp)
  remove(temp)
 }
}
```

#OTU Counts by sample
Determine total OTUs
```{r}
taxa_Genus_greengenes$Total_OTUs <- rowSums(taxa_Genus_greengenes)

```

#Observed to Expected Counts
```{r}
tp_fp_fn_samplelevel<- function(db,tl,ct){
 sample_list<-intersect(rownames(get(paste("taxa",tl,db,sep="_"))),rownames(subset(get(paste("metadata",tl,db,sep="_")),Source.Descrip==ct)))
 exp_taxa_list<-rownames(get(paste("expected_taxa",tl,sep="_"))[ get(paste("expected_taxa",tl,sep="_"))[[ct]] !='A' , ])
 unexp_taxa_list<-setdiff(colnames(get(paste("taxa",tl,db,sep="_"))),exp_taxa_list)
 unexp_taxa_list<-unexp_taxa_list[-length(unexp_taxa_list)] #Remove Total_OTUs column
 
 for (a in sample_list){
  fp=0
  fn=0
  tp=0
  
  taxa_db<-get(paste("taxa",tl,db,sep="_"))
  
  #Run through expected taxa list
  for (b in exp_taxa_list){
   otu_count<-taxa_db[a,b]

   
   if(is.null(otu_count) || otu_count==0 || is.na(otu_count)){
    fn=fn+1

   } else if (otu_count>0){
    tp=tp+1
   }
  }
  
  #Run through all taxa not expected
  for (b in unexp_taxa_list){
   otu_count<-taxa_db[a,b]
   
   if(otu_count==0){
    next;
   } else if (otu_count>0){
    fp=fp+1
   }
  }
  
  temp[a,"ControlType"]<-ct
  temp[a,"Expected"]<-length(exp_taxa_list)
  temp[a,paste("TP",db,tl,sep="_")]<-tp
  temp[a,paste("FP",db,tl,sep="_")]<-fp
  temp[a,paste("FN",db,tl,sep="_")]<-fn
  temp[a,paste("TAR",db,tl,sep="_")]<-tp/(tp+fp)
  temp[a,paste("TDR",db,tl,sep="_")]<-tp/(tp+fn)
  temp[a,paste("F1",db,tl,sep="_")]<-2*((tp/(tp+fp))*(tp/(tp+fn)))/((tp/(tp+fp))+(tp/(tp+fn)))
 }
 
 return(temp)
}

temp<-data.frame()

control_type<-c("MSA1000","MSA1001","MSA1002","MSA1003","D6305","D6306","D6311")

for(a in reference_db){
 for (b in taxa_levels){
  for (c in control_type){
   temp<-tp_fp_fn_samplelevel(a,b,c)
  }
 }
}

write.csv(temp,paste(output_location,"\\Taxa\\Taxonomy_tar_tdr.csv",sep=""))

remove(temp)

```

#Observed to Expected Counts
```{r}
samplelist_seqcontrols<-rownames(otu_baseline_complete)
observed_baseline_seqcontrols<- data.frame()
taxa_observed=colnames(otu_baseline_complete)
taxa_observed=taxa_observed[-length(taxa_observed)]#Remove Total_OTUs

observed_count=0
notobserved_count=0

#Individual Samples
for (a in samplelist_seqcontrols){
 control_type <- as.String(metadata_baseline[a,"Source.Descrip"])
 taxa_temp <- control_expect[,c("Gram",control_type)]
 taxa_temp <- row.names(subset(taxa_temp,!(taxa_temp[,control_type]=="A")))
 
 for (b in taxa_temp){ #for all expected taxa, determine which are observed
  otu_count <- otu_baseline_complete[a,b]
  
  if(!(is.na(observed_count) || is.null(otu_count) || otu_count==0)){ #for all taxa with a positive OTU count
    observed_count= observed_count+1
  } else{
   notobserved_count=notobserved_count+1
  }
 }
 
 observed_baseline_seqcontrols[a,"Observed"] <- observed_count
 observed_baseline_seqcontrols[a,"Expected"] <- length(taxa_temp)
 observed_baseline_seqcontrols[a,"Observed_NotExpected"] <- sum(otu_baseline_complete[a,]>1)-1-observed_count #total-1 for total OTU column
 observed_baseline_seqcontrols[a,"Expected_NotObserved"] <- notobserved_count
 observed_baseline_seqcontrols[a,"Source.Descrip"] <- metadata_baseline[a,"Source.Descrip"]
 observed_count=0
 notobserved_count=0
}

#Average by Source.Descrip
observed_count=0
observednotexp_count=0
notobserved_count=0
count=0
source_list<-unique(observed_baseline_seqcontrols$Source.Descrip)

for (a in source_list){
 for (b in samplelist_seqcontrols){
  control_type <- as.String(metadata_baseline[b,"Source.Descrip"])
  if(a==control_type){
   observed_count<-observed_baseline_seqcontrols[b,"Observed"]+observed_count
   observednotexp_count<-observed_baseline_seqcontrols[b,"Observed_NotExpected"]+observednotexp_count
   notobserved_count<-observed_baseline_seqcontrols[b,"Expected_NotObserved"]+notobserved_count
   expected_count<-observed_baseline_seqcontrols[b,"Expected"]
   count=count+1
  }
 }
 observed_baseline_seqcontrols[a,"Observed"]<-observed_count/count
 observed_baseline_seqcontrols[a,"Expected"]<-expected_count
 observed_baseline_seqcontrols[a,"Observed_NotExpected"]<-observednotexp_count/count
 observed_baseline_seqcontrols[a,"Expected_NotObserved"]<-notobserved_count/count
 observed_baseline_seqcontrols[a,"Source.Descrip"]<-a
 
 observed_count=0
 observednotexp_count=0
 notobserved_count=0
 count=0
}

write.csv(observed_baseline_seqcontrols,paste(output_location,"Data\\Baseline\\observed_baseline_",taxa_levels,"_seqcontrols.csv",sep=""))
```

#Relative Abundance  - Seq Controls
```{r}
relabun_baseline_seqcontrols<-data.frame()

#Complete Relative Abundance
samplelist_seqcontrols<-rownames(otu_baseline_complete)
taxa_list <- colnames(otu_baseline_complete)
taxa_list<-taxa_list[-(length(taxa_list))]
taxa_list<-append(taxa_list,rownames(control_expect))

for (a in samplelist_seqcontrols){
 for (b in taxa_list){
  
  relabun <- otu_baseline_complete[a,b]
  
  if(!(is.na(relabun) || is.null(relabun) || relabun==0)){
   relabun_baseline_seqcontrols[a,b] <- otu_baseline_complete[a,b]/otu_baseline_complete[a,"Total_OTUs"]
   relabun_baseline_seqcontrols[a,"Source.Descrip"]<-as.character(metadata_baseline[a,"Source.Descrip"])
  }
  control_type<-as.character(metadata_baseline[a,"Source.Descrip"])
  relabun_baseline_seqcontrols[control_type,b]<-as.character(control_expect[b,control_type])
  relabun_baseline_seqcontrols[control_type,"Source.Descrip"]<-control_type
 }
}

relabun_baseline_seqcontrols[is.na(relabun_baseline_seqcontrols)]=0 #replace na's with 0
relabun_baseline_seqcontrols[relabun_baseline_seqcontrols=="A"]=0 #replace A's with 0
write.csv(relabun_baseline_seqcontrols,paste(output_location,"Data\\Baseline\\relabun_baseline_seqcontrols.csv",sep=""))
```

#6 Plot graph - IntraControl Variability
For each kit, show variability, and map
```{r}
ordu = ordinate(physeq_filt_seqcontrols, "PCoA", "unifrac", weighted=TRUE)
plot_ordination(physeq_filt_seqcontrols, ordu, color="Source.Descrip")
```