---
title: "R Notebook"
output: word_document
editor_options: 
  chunk_output_type: console
---
#To Update
```{r}
project_name="Project_NP0084-MB4_5_pt6_2"
manifest_name="metadata_Summary_3.csv"
otu_name="otu_Summary_3.csv"
sample_depth= 20000
```

#Load required libraries
############### 
```{r}
library("biom")
library(data.table)
library(tm)
library(vegan)
library("biom")
library(tidyr)
library(ggplot2)
library(cowplot)
library(scales)
library(phyloseq)
library(qiime2R)
library(tibble)
library(gridExtra)
library(tidyverse)
```

#Analysis
###############
```{r}
plot_diversity<-function(phyobject,filter,subfeat){
 p<-plot_richness(phyobject, x=filter) + geom_boxplot()
 file_name =paste(output_location,"Graphs\\alphadiv_",filter,"_",subfeat,".tiff",sep="")
 tiff(file_name, width=800)
 print(p)
 dev.off()
} 

subset_list<-c("Study")
physeq_study<-subset_samples(physeq_scale, Sample.Type %in% subset_list)

subset_list<-c("TissueLyzer","Vertical","Plate Adaptor")
physeq_study<-subset_samples(physeq_study, Homo.Method %in% subset_list)

subset_list<-c("DZ35298","Study")
physeq_study<-subset_samples(physeq_study, Source.Descrip %in% subset_list)

alpha_plots<-c("Ext.Kit")

for (a in alpha_plots){
 plot_diversity(physeq_study,a,"studyonly_std")
}


subset_list<-c("Study")
physeq_study<-subset_samples(physeq_scale, Sample.Type %in% subset_list)

subset_list<-c("MagAttract PowerMicrobiome Kit")
physeq_study<-subset_samples(physeq_study, Ext.Kit %in% subset_list)

subset_list<-c("DZ35298","Study")
physeq_study<-subset_samples(physeq_study, Source.Descrip %in% subset_list)

unique(sample_data(physeq_study)$Homo.Method)
unique(sample_data(physeq_study)$Sample.Type)


alpha_plots<-c("Homo.Method")

for (a in alpha_plots){
 plot_diversity(physeq_study,a,"studyonly_mbexamp")
}

#PCOA plots
subset_list<-c("Study")
physeq_study<-subset_samples(physeq_scale, Sample.Type %in% subset_list)
subset_list<-c("TissueLyzer","Vertical","Plate Adaptor")
physeq_study<-subset_samples(physeq_study, Homo.Method %in% subset_list)
subset_list<-c("DZ35298","Study")
physeq_study<-subset_samples(physeq_study, Source.Descrip %in% subset_list)



#######################
## Bray-Curtis
#######################
physeq_pcoa <- ordinate(
  physeq = physeq_study, 
  method = "PCoA", 
  distance = "bray"
)
## Plot by Ext.Kit
p<- plot_ordination(
  physeq = physeq_study,
  ordination = physeq_pcoa,
  color = "Ext.Kit",
  title = "PCoA of Ext.Kit (Bray-Curtis)"
) + 
  scale_color_manual(values = c("#a65628", "red", "#ffae19",
    "#4daf4a", "#1919ff", "darkorchid3", "magenta")
  ) +
  geom_point(aes(color = Ext.Kit), alpha = 0.7, size = 6) +
  geom_point(colour = "grey90", size = 1.5)
file_name =paste(output_location,"Graphs\\bray_baseline_study_study_std.tiff",sep="")
tiff(file_name, width=800)
print(p)
dev.off()

## Plot by Source.Descrip
p<- plot_ordination(
  physeq = physeq_study,
  ordination = physeq_pcoa,
  color = "Source.Descrip",
  title = "PCoA of Source.Descrip (Bray-Curtis)"
) + 
  scale_color_manual(values = c("#a65628", "red", "#ffae19",
    "#4daf4a", "#1919ff", "darkorchid3", "magenta")
  ) +
  geom_point(aes(color = Source.Descrip), alpha = 0.7, size = 6) +
  geom_point(colour = "grey90", size = 1.5)
file_name =paste(output_location,"Graphs\\bray_baseline_study_std_source.tiff",sep="")
tiff(file_name, width=800)
print(p)
dev.off()

## Plot by Homo.Method
p<- plot_ordination(
  physeq = temp,
  ordination = physeq_pcoa,
  color = "Homo.Method",
  title = "PCoA of Homo.Method (Bray-Curtis)"
) + 
  scale_color_manual(values = c("#a65628", "red", "#ffae19",
    "#4daf4a", "#1919ff", "darkorchid3", "magenta")
  ) +
  geom_point(aes(color = Homo.Method), alpha = 0.7, size = 6) +
  geom_point(colour = "grey90", size = 1.5)
file_name =(paste(project_location,"\\Output\\R\\Data\\Baseline\\bray_baseline_study_homomethod.tiff"))
tiff(file_name, width=800)
print(p)
dev.off()
```

#8 - Plot Interkit Sample Variability
```{r}
#Sort genus list alphabetically
genus_found<-sort(genus_found)

#Create list for plots, start counter
plot_list <- list()
i=1

#For each of the control types
for (a in control_types){
 
 #For each kit
 for (b in kit_types){
  
  #Create new dataframe and start counter
  temp<-data.frame()
  count=1
    
  ###Create list of sample ids with specific variables
  temp2 <- subset(samples_variables_f,Kit==b)
  temp2 <- subset(temp2,Type==a)
  sample_list <- unique(temp2$NephID)
  
  #For each sample in list
  for (c in sample_list){
   
   #For each genus
   for (d in genus_found){
    
    #Determine the abundance value
    value <- samples_obs_abund[d,c]
    aliquot<-samples_variables_f[c,"AliquotNumber"]
   
    #If the value is null or smaller than 1 X10-5, skip
    if(is.na(value) | is.null(value) | value<0.0000000001){
     next}
    
    #Otherwise add to datatable
    else{
     temp[count,"Abundance"]<-value
     temp[count,"Genus"]<-d
     
     if(aliquot=="None"){
      temp[count,"SampleID"]<-c
     }else{
      temp[count,"SampleID"]<-aliquot
     }
     count=count+1
     }
   }
  }
  
  #Create file name
  file_name <- paste ("Data/Study/SampleVari",b,a,sep = "_")
  file_name <- paste(file_name,".csv",sep="")
  
  #Sort and save the datatable
  temp<-temp[order(temp$SampleID), ]
  write.csv(temp,file_name)
  
  #Create graph title
  graph_title<-paste(a,b,sep="_")
    
  #Create Graph for the datatable
  graph_new<- ggplot(temp,aes(x =SampleID , y = Abundance, fill = Genus)) + 
   geom_bar(position = position_fill(), stat = "identity") +
   scale_y_continuous(labels = percent_format())+
   labs(title=graph_title, x="Sample ID", y= "Relative Abundance")+
   theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
   #+ theme(legend.position = "bottom",legend.box = "vertical")
   theme(legend.position = "none") ##Remove Legend
  
  graph_new  
  plot_list[[i]] = graph_new
  i=i+1
    
  #Reset data table
    temp<-data.frame()
  }
}

#Print the plots
i=1
for (a in control_types){
 
 for (b in kit_types){
  
  #Create file name
  file_name<-paste("Interkit Variability",a,b,sep="_")
  file_name<-paste("Data/Graphs/",file_name,".tiff",sep="")
  tiff(file_name)
  print(plot_list[[i]])
  dev.off()
  i=i+1
 }
}
```

#9 - Plot All Sample Variability in individual kit graphs
```{r}
#Create list for plots, start counter
plot_list <- list()
i=1

#For each of the control types
for (a in control_types){
 
 #Create new dataframe and start counter
 temp<-data.frame()
 count=1
    
 ###Create list of sample ids with specific variables
 temp2 <- subset(samples_variables_f,Type==a)
 sample_list <- unique(temp2$NephID)
 
 #For each sample in list
 for (b in sample_list){
  
  #For each genus
  for (c in genus_found){
   
   #Determine the abundance value
   value <- samples_obs_abund[c,b]
   aliquot<-samples_variables_f[b,"AliquotNumber"]
   
   #If the value is null or smaller than 1 X10-7, skip
   if(is.na(value) | is.null(value) | value<0.000000000001){
    next}
    
   #Otherwise add to datatable
   else{
    temp[count,"Abundance"]<-value
    temp[count,"Genus"]<-c
    
    if(aliquot=="None"){
     
     temp[count,"SampleID"]<-b
     }else{
      
      #Add kit info
      aliquot <- paste(aliquot,samples_variables_f[b,"Kit"],sep="_")
      temp[count,"SampleID"]<-aliquot
     }
    count=count+1
   }
  }
 }
 
 #Create file name
 file_name <- paste ("Data/Study/StudyVari",a,sep = "_")
 file_name <- paste(file_name,".csv",sep="")
 
 #Sort and save the datatable
 temp<-temp[order(temp$SampleID), ]
 write.csv(temp,file_name)
  
 #Create graph title
 graph_title<-paste(a,sep="_")
 
 #Create Graph for the datatable
 graph_new<- ggplot(temp,aes(x =SampleID , y = Abundance, fill = Genus)) + 
  geom_bar(position = position_fill(), stat = "identity") +
  scale_y_continuous(labels = percent_format())+
  labs(title=graph_title, x="Sample ID", y= "Relative Abundance")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  #+ theme(legend.position = "bottom",legend.box = "vertical")
  theme(legend.position = "none") ##Remove Legend
  
 plot_list[[i]] = graph_new
 i=i+1
    
 #Reset data table
   temp<-data.frame()
}

#Print the plots
i=1
for (a in control_types){
 
 #Create file name
 file_name<-paste("Interstudy Variability",a,sep="_")
 file_name<-paste("Data/Graphs/",file_name,".tiff",sep="")
 tiff(file_name)
 print(plot_list[[i]])
 dev.off()
 i=i+1
}
```

#9 - Plot All Sample Variability in individual kit graphs
```{r}
#Create list for plots, start counter
plot_list <- list()
i=1

#Create new dataframe and start counter
temp<-data.frame()
count=1
    
for (a in kit_types){
 ###Create list of sample ids with specific variables
 temp2 <- subset(samples_variables_f,Type=="Study" & Kit==a)
 sample_list <- unique(temp2$NephID)
 
 for (b in sample_list){
  
  for (c in genus_found){
   temp[count,"Value"]<-samples_obs_abund[c,b]
   temp[count,"Kit"]<-a
   temp[count,"Aliquot"]<-samples_variables_f[b,"AliquotNumber"]
   temp[count,"SampleID"]<- paste(a,samples_variables_f[b,"AliquotNumber"],sep="_")
   temp[count,"ID"]<-b
   temp[count,"Genus"]<-c
   count=count+1
  }
 }
}
write.csv(temp,"temp4.csv")
#Remove DSP kit samples


temp<-read.csv("temp4.csv",header = TRUE)

#Create Graph for the datatable
graph_title <- "Fecal Samples by Kit by Aliquot ID"
graph_new<- ggplot(temp,aes(x =SampleID , y = Value, fill = Genus)) + 
  geom_bar(position = position_fill(), stat = "identity") +
  scale_y_continuous(labels = percent_format())+
  labs(title=graph_title, x="Sample ID", y= "Relative Abundance")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  #+ theme(legend.position = "bottom",legend.box = "vertical")
  theme(legend.position = "none") ##Remove Legend
  
plot_list[[i]] = graph_new
 
#Print the plot
file_name <- "StudyVariability"
file_name<-paste("Data/Graphs/",file_name,".tiff",sep="")
tiff(file_name)
print(plot_list[[i]])
dev.off()

```



#10 - Plot all sample variability in one graph
```{r}
#Edit the data to be able to numerically order the aliquots
temp<-read.csv("Data/Study/StudyVari_Study_Edited(Aliquot).csv",header = TRUE)

#Edit the data to be able to numerically order the aliquots by kit
temp<-read.csv("Data/Study/StudyVari_Study_Edited(Kit).csv",header = TRUE)
temp$X<- factor(temp$X, levels=temp$X)

#Create a plot for 
ggplot(temp,aes(x =SampleID , y = Abundance, fill = Genus)) + 
 geom_bar(position = position_fill(), stat = "identity") +
 scale_y_continuous(labels = percent_format())+
 labs(title="Fresh-Frozen Fecal Study Samples", x="Extraction Kit_Aliquot ID", y= "Relative Abundance")+
 theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
 #+ theme(legend.position = "bottom",legend.box = "vertical")
 theme(legend.position = "none") ##Remove Legend

```